blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_index_page, name='index'),  # URL pattern for the main blog page
    # Add more URL patterns as needed for other blog pages
    # path('<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),

]

staging/urls.py
from django.urls import path
from . import views
from .views import menu_page  # Make sure this import is correct
from .views import about_page  # Make sure this import is correct
app_name = 'staging'

urlpatterns = [
    path('', views.staging_home, name='home'),
    path('explore/',views.explore,name='explore'),
    path('about/', views.about_page, name='about_page'),
    path('services/', views.services_page, name='services_page'),
    path('achievements/', views.achievements_page, name='achievements_page'),
    path('blog/', views.blog_page, name='blog_page'),
    path('contact/', views.contact_page, name='contact_page'),
    # ... other staging URLs ...
]

achievements/models.py
from django.db import models
from wagtail.fields import RichTextField, StreamField
from wagtail import blocks
from wagtail.models import Page

from wagtail.admin.panels import InlinePanel, FieldPanel, MultiFieldPanel
# Create your models here.


class AchievementPage(Page):
    achivement = StreamField(
        [('html', blocks.RawHTMLBlock())], blank=True, use_json_field=True)

    content_panels = Page.content_panels + [
        FieldPanel('achivement', classname="full"),]

    template = "staging/achievements.html"

    class Meta:
        verbose_name = "Achievement Page"
        verbose_name_plural = "Achievement Pages"

blog/models.py
from django.db import models
from django import forms
from wagtail.snippets.models import register_snippet
from modelcluster.fields import ParentalKey, ParentalManyToManyField
from modelcluster.contrib.taggit import ClusterTaggableManager
from taggit.models import TaggedItemBase
from wagtail.models import Page, Orderable
from wagtail.fields import RichTextField, StreamField
from wagtail.admin.panels import FieldPanel, InlinePanel, MultiFieldPanel
from wagtail.images.blocks import ImageChooserBlock
from wagtail.blocks import RichTextBlock, TextBlock, StructBlock
from wagtail.search import index
from wagtail.images.models import Image
from wagtail.images.widgets import AdminImageChooser

class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        'BlogPage',
        related_name='tagged_items',
        on_delete=models.CASCADE
    )

class BlogIndexPage(Page):
    intro = RichTextField(blank=True)

    def get_context(self, request):
        context = super().get_context(request)
        tag = request.GET.get('tag')
        blogpages = BlogPage.objects.filter(tags__name=tag) if tag else BlogPage.objects.all()
        context['blogpages'] = blogpages
        return context

@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(max_length=255)
    icon = models.ForeignKey(
        'wagtailimages.Image', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='+'
    )

    panels = [
        FieldPanel('name'),
        FieldPanel('icon'),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'blog categories'

class BlogPage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)
    header_image = models.ForeignKey(
        Image,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    blog_title = models.CharField(max_length=255, default="title")
    blog_meta = models.CharField(max_length=255, default="blog_meta")
    blog_content = StreamField([
        ('paragraph', RichTextBlock()),
        ('code', TextBlock()),
    ], use_json_field=True, default="")
    comments = StreamField([
        ('comment', StructBlock([
            ('name', TextBlock()),
            ('date', TextBlock()),
            ('comment', TextBlock()),
        ])),
    ], use_json_field=True, blank=True)
    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    categories = ParentalManyToManyField('blog.BlogCategory', blank=True)

    def main_image(self):
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None

    @staticmethod
    def get_recent_posts():
        return BlogPage.objects.live().order_by('-first_published_at')[:5]

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('tags'),
            FieldPanel('categories', widget=forms.CheckboxSelectMultiple),
        ], heading="Blog information"),
        FieldPanel('intro'),
        FieldPanel('body'),
        FieldPanel('header_image', widget=AdminImageChooser),
        FieldPanel('blog_title'),
        FieldPanel('blog_meta'),
        FieldPanel('blog_content'),  # Use FieldPanel for StreamField
        FieldPanel('comments'),  # Use FieldPanel for StreamField
        InlinePanel('gallery_images', label="Gallery images"),
        InlinePanel('related_posts', label="Related posts"),
    ]

    template = "staging/blog-content.html"

class BlogPageGalleryImage(Orderable):
    page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        FieldPanel('image'),
        FieldPanel('caption'),
    ]

@register_snippet
class RelatedPost(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()

    panels = [
        FieldPanel('title'),
        FieldPanel('url'),
    ]

    def __str__(self):
        return self.title

class BlogPageRelatedPosts(models.Model):
    page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='related_posts')
    related_post = models.ForeignKey(RelatedPost, on_delete=models.CASCADE)

    panels = [
        FieldPanel('related_post'),
    ]

@register_snippet
class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

# class BlogPageTag(models.Model):
#     page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='blog_page_tags', null=True)
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

#     panels = [
#         FieldPanel('tag'),
#     ]

contacts/models.py
from django.db import models
from wagtail.fields import RichTextField, StreamField
from wagtail import blocks
from wagtail.models import Page

from wagtail.admin.panels import InlinePanel, FieldPanel, MultiFieldPanel
# Create your models here.

class ContactPage(Page):
    contact = StreamField([('html', blocks.RawHTMLBlock())],blank=True, use_json_field=True)

    content_panels = Page.content_panels + [
        FieldPanel('achivement', classname="full"),]

    template = "staging/contacts.html"



    class Meta:
        verbose_name = "contacts Page"
        verbose_name_plural = "contacts Pages"

home/models.py
from django.db import models

from wagtail.models import Page
from wagtail.fields import RichTextField
from wagtail.admin.panels import FieldPanel


class HomePage(Page):
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]

service/models.py
from django.db import models
from wagtail.models import Page
from wagtail.fields import RichTextField, StreamField
from wagtail.admin.panels import FieldPanel
from wagtail.blocks import CharBlock, RichTextBlock, StructBlock
from wagtail.images.blocks import ImageChooserBlock
from wagtail import blocks

class ServiceBlock(StructBlock):
    image = ImageChooserBlock(required=True)
    title = CharBlock(required=True)
    description = RichTextBlock(required=True)

    class Meta:
        icon = "placeholder"
        label = "Service"

class ServiceTitleBlock(StructBlock):
    title = CharBlock(required=True)

    class Meta:
        icon = "title"
        label = "Service Title"

class ApplicationBlock(StructBlock):
    title = CharBlock(required=True)
    description = RichTextBlock(required=True)

    class Meta:
        icon = "doc-full"
        label = "Application"

class ServicePage(Page):

    first_part = StreamField([('html', blocks.RawHTMLBlock())],blank=True, use_json_field=True)
    second_part = StreamField([('html', blocks.RawHTMLBlock())],blank=True, use_json_field=True)
    third_part = StreamField([('html', blocks.RawHTMLBlock())],blank=True, use_json_field=True)

    content_panels = Page.content_panels + [
        FieldPanel('first_part'),
        FieldPanel('second_part'),
        FieldPanel('third_part'),
    ]

    template = "staging/services.html"

    class Meta:
        verbose_name = "Service Page"
        verbose_name_plural = "Service Pages"

staging/models.py
from django.db import models

class Menu(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    # Add any other fields you need

achievements/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404
from .models import AchievementPage


def achievement_page_view(request):
    # Assuming there is only one ServicePage or you want the first one
    context = {'page': None}
    achievement_page = AchievementPage.objects.all().first()
    if achievement_page:
        context = {
            'page': achievement_page,
        }

    return render(request, 'staging/achievements.html', context)

blog/views.py
from django.shortcuts import render
from .models import BlogPage
from wagtail.models import Page
from wagtail.contrib.routable_page.models import RoutablePageMixin, route

def blog_index_page(request):
    blogpages = BlogPage.objects.live().order_by('-date')
    context = {'blogpages': blogpages}
    return render(request, 'staging/blog-main.html', context)

class BlogDetailView(RoutablePageMixin, Page):
    template = "staging/blog-content.html"

    @route(r'^$', name='blog_detail')
    def blog_detail(self, request):
        context = self.get_context(request)
        context['blogpage'] = BlogPage.objects.get(slug=self.slug)
        return render(request, self.template, context)

contacts/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render


def explore_page(request):
  return render(request, 'staging/explore.html')

service/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404
from .models import ServicePage

def service_page_view(request):
    # Assuming there is only one ServicePage or you want the first one
    context = {
        'page': None,
    }
    service_page = ServicePage.objects.all().first()
    if service_page:
        context = {
            'page': service_page,
        }
    return render(request, 'staging/services.html', context)

staging/views.py
from django.shortcuts import render

def staging_home(request):
    return render(request, 'staging/home.html')
def menu_page(request):
    return render(request, 'staging/menu.html')
def about_page(request):
    return render(request, 'staging/about.html')
def achievements_page(request):
    return render(request, 'staging/achievements.html')
def blog_page(request):
    return render(request, 'staging/blog.html')
def contact_page(request):
    return render(request, 'staging/contact.html')
def services_page(request):
    return render(request, 'staging/services.html')
def explore(request):
    return render(request, 'staging/explore.html')

staging/templates/staging/achievements.html
{% extends 'staging/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %} Home {% endblock %}
<!-- loading from the static folder? -->
 {% load wagtailcore_tags %} {% block page-css %}
<!-- CSS and other static file references go here -->
<link rel="stylesheet" href="{% static 'staging/css/home.css' %}" />
{% endblock %}

<!-- adding title to base.html -->
{% block content %}
<div class="container flex-archi-main-container bg-effect">
  <a href="{% url 'staging:explore' %}" class="white-btn"
    ><i class="bi bi-plus"></i>Explore</a
  >
  {% if page.achivement %}
  {{ page.achivement|safe }}
  {% else %}
  <div class="container-fluid">
    <div class="container clm-archi">
      <p class="product light-blue-text mb-negative">Achievement</p>
      <img
        src="{% static 'staging/achievement/img/dotwhite.png' %}"
        alt=""
        class="dor-line"
      />
      <h1 class="product text-center">Certifications</h1>
    </div>
    <div class="container flex-archi-container">
      <div class="row justify-center">
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="card-hover">
            <img
              src="{% static 'staging/achievement/img/archicard1.png' %}"
              class="img-fluid"
            />
            <div class="on-hover-appear">
              <p>Microsoft Certified</p>
              <h6>Azure Solutions Architech</h6>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="hoverElement">
            <img
              src="{% static 'staging/achievement/img/Azure Fundamental.png' %}"
              class="img-fluid bg-white-card"
            />
          </div>
          <div class="on-hover-appear" id="hiddenElement">
            <p>Microsoft Certified</p>
            <h6>Azure Administrator Associate</h6>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="hoverElement2">
            <img
              src="{% static 'staging/achievement/img/Azure Admin.png' %}"
              class="img-fluid"
            />
          </div>
          <div class="on-hover-appear" id="hiddenElement2">
            <p>Microsoft Certified</p>
            <h6>Azure Developer Associate</h6>
          </div>
        </div>
      </div>
      <div class="row justify-center">
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="hoverElement3">
            <img
              src="{% static 'staging/achievement/img/Azure Developer.png' %}"
              class="img-fluid"
            />
          </div>
          <div class="on-hover-appear" id="hiddenElement3">
            <p>Microsoft Certified</p>
            <h6>Azure Developer Associate</h6>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="hoverElement4">
            <img
              src="{% static 'staging/achievement/img/Azure Fundamental.png' %}"
              class="img-fluid"
            />
          </div>
          <div class="on-hover-appear" id="hiddenElement4">
            <p>Microsoft Certified</p>
            <h6>Azure Fundamentals Developer</h6>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="card-archi" id="hoverElement5">
            <img
              src="{% static 'staging/achievement/img/Azure Admin.png' %}"
              class="img-fluid"
            />
          </div>
          <div class="on-hover-appear" id="hiddenElement5">
            <p>Microsoft Certified</p>
            <h6>Azure Solutions Architech</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

</div>
{% endblock %} {% block page-js %}
<script src="{% static 'staging/js/hover.js' %}"></script>

{% endblock %}

staging/templates/staging/blog-content.html
{% load static %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>{{ page.blog_title }} - Home </title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'staging/images/favicon/favicon.ico' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="{% static 'staging/css/blog_details.css' %}" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-HVDRGM3PE4"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'G-HVDRGM3PE4');
    </script>
</head>
<body class="home">
<section>
  <div class="container-fluid">
    <a href="{% url 'staging:explore' %}" class="white-btn"><i class="bi bi-plus"></i>Explore</a>
    <div class="container-fluid p-0">
      <div class="blog-header">
        {% if page.header_image %}
        {% image page.header_image fill-1500x600 class="header-image" %}
        {% else %}
        <img src="{% static 'staging/blog/img/blog-card.png' %}" alt="Blog Header Image" class="header-image">
        {% endif %}
        <div class="overlay">
          <div>
            <div class="blog-title">{{ page.blog_title }}</div>
            <div class="blog-meta">By Mezba Uddin | {{ page.date }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <main class="col-md-9">
        <div class="blog-content">
          {% load wagtailcore_tags %}
          {% for block in page.blog_content %}
          {% if block.block_type == 'code' %}
    <pre><code>{{ block.value }}</code></pre>
  {% else %}

            {{ block }}
          {% endif %}
            {% endfor %}
        </div>

        <div class="comment-section">
          <h3>Comments</h3>
          <div class="clearfix"></div>
          {% for comment in page.comments %}
          <div class="comment">
            <strong>{{ comment.name }}</strong>
            <span class="text-muted">- {{ comment.date }}</span>
            <p>{{ comment.comment }}</p>
          </div>
          {% endfor %}

          <h5>Leave a Comment</h5>
          <form>
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" id="name" required />
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" required />
            </div>
            <div class="mb-3">
              <label for="comment" class="form-label">Comment</label>
              <textarea class="form-control" id="comment" rows="4" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </main>

      <aside class="col-md-3">
        <div class="sidebar">
          <div class="mb-4">
            <h5>Related Posts</h5>
            <ul class="list-unstyled">
              {% for related_post in page.related_posts.all %}
              <li><a href="{{ related_post.url }}">{{ related_post.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
          <div class="mb-4">
            <h5>Recent Posts</h5>
            <ul class="list-unstyled">
            {% if page.get_recent_posts %}
              {% for post in page.get_recent_posts %}
              <li><a href="{% url 'blog_detail' post.slug %}">{{ post.title }}</a></li>
              {% endfor %}
            {% endif %}
            </ul>
          </div>
          <div>
            <h5>Tags</h5>
            {% if page.tags %}
            <div class="tag-cloud">
              {% for tag in page.tags.all %}
              <a href="#">{{ tag.name }}</a>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
      </aside>
    </div>
  </div>
</section>

<script>
  function openFullscreenContainer() {
    document.getElementById("fullscreen-container").style.display = "flex";
  }
  function closeFullscreenContainer() {
    document.getElementById("fullscreen-container").style.display = "none";
  }
  function openFullscreenContainer2() {
    document.getElementById("bg-darkgreen").style.display = "block";
  }
  function openFullscreenContainer3() {
    document.getElementById("blog-main-container").style.display = "block";
  }
</script>
<script src="{% static 'staging/js/expend.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>

staging/templates/staging/blog-main.html
{% extends 'staging/base.html' %}
{% block title %} Blog {% endblock %}

{% load static %} {% load wagtailcore_tags %}

{% block page-css %}
<link rel="stylesheet" href="{% static 'staging/css/home.css' %}" />
{% endblock %}

{% block content %}
<section>
    <div class="container-fluid flex-blog-main-container">
        <a href="{% url 'staging:explore' %}" class="white-btn">
            <i class="bi bi-plus"></i>Close
        </a>
        <div class="container">
            <div class="container flex-blog">
                <img src="{% static 'staging/blog/img/Latest News.png' %}" alt="" class="archititleimg img-fluid" />
            </div>
            <div class="container clm-blog">
                <h6 class="text-white">Product</h6>
                <h1 class="text-white my-2">
                    Product Management 101: Navigating the Path to Success
                </h1>
                <p class="text-white mt-3">
                    In the fast-paced world of technology and business, effective product
                    management is the linchpin that holds a company's vision, strategy,
                    and execution together. Product managers play a crucial role in
                    bringing innovative ideas to life and ensuring that they resonate with
                    ...
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4 mt-5">
            {% for blog_page in blogpages %}
            <div class="col">
                <div class="card-blog">
                    <img src="{% static 'staging/blog/img/blog-card.png' %}" class="card-img-top" alt="..." />
                    <div class="card-body">
                        {% for tag in blog_page.tags.all %}
                            <a href="{{ blog_page.get_absolute_url }}" class="card-link">
                                <i class="bi bi-cpu"></i>{{ tag.name }}
                            </a>
                        {% endfor %}
                        <h4 class="card-title">{{ blog_page.blog_title }}</h4>
                        <p class="card-text">
                            {{ blog_page.intro|truncatewords:30 }}
                        </p>
                        <a href="#" class="card-link">
                            <i class="bi bi-person"></i>Mezba Uddin
                        </a>
                        <a href="#" class="card-link">
                            <i class="bi bi-calendar"></i>
                            {{ blog_page.date|date:"F j, Y" }}
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

staging/templates/staging/explore.html
{% extends 'staging/base.html' %} {% block title %} Explore {% endblock %}
<!-- loading from the static folder? -->
{% load static %} {% load wagtailcore_tags %} {% block page-css %}
<!-- CSS and other static file references go here -->
<link rel="stylesheet" href="{% static 'staging/css/home.css' %}" />
{% endblock %}

<!-- adding title to base.html -->
{% block content %}
<section class="fullwidth-menuclose" id="fullscreen-container">
	<a href="{% url 'staging:home' %}" class="close-btn "><i class="bi bi-plus"></i>Close</a>
	<div class="container-fluid bigdisplay">
	<div class="row">
		<div class="col-sm-6  container-mix">
			<div class="row">
				<div class="col-lg-12   about-container">
					<a href="{% url 'resume_page' %}">
						<h1 class="index-text">About</h1>
						<p class="product-font text-white">Know me more</p>
						<hr class="line-white">
					</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<div class="row services-container">
						<a href="{% url 'service_page' %}">
							<h1 class="index-text text-center">Services</h1>
							<p class="product-font text-ligh-white  text-center">Service i provide</p>
							<hr class="line-dark">
						</a>
					</div>
					<div class="container-fluid">
						<div class="row">
							<div class="col-lg-6 col-sm-6  home-container">
								<a href="{% url 'staging:home' %}">
									<h5 class="index-text">Home</h5>
								</a>
							</div>
							<div class="col-sm-6 blog-container">
								<a href="{% url 'staging:blog_page' %}">
									<h3 class="index-text text-green">Blog</h3>
									<p class="product-font text-product-index-p text-dark">What’s New</p>
									<hr class="line-dark">
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-6 col-md-12  contact-container">
					<a href="{% url 'staging:contact_page' %}">
						<h1 class="index-text text-center">Contact</h1>
						<p class="product-font text-product-index-p   text-center">Get in touch</p>
						<hr class="line-dark">
					</a>
				</div>
			</div>
		</div>
		<div class="col-sm-6   archi-container">
			<a href="{% url 'staging:achievements_page' %}">
				<h1 class="index-text text-center">Achievement</h1>
				<p class="product-font text-product-index-p text-center">My Latest Work</p>
				<hr class="line-dark">
			</a>
		</div>
	</div>
</section>
{% endblock %}

staging/templates/staging/menu.html
{% extends 'staging/base.html' %}

<!-- loading from the static folder? -->
{% load static %}
{% load wagtailcore_tags %}

<!-- adding title to base.html -->
{% block title %}
Menue
{% endblock %}

{% block content %}
<!-- adding css file -->

  
    <div class="menu">
      <div class="div">
        <a href="{% url 'staging:about_page' %}">
          <div class="about">
            <div class="group">
              <div class="text-wrapper">About</div>
              <div class="text-wrapper-2">Know me more</div>
              <div class="rectangle"></div>
            </div>
          </div>
        </a>
        <a href="{% url 'staging:contact_page' %}">
          <div class="contact">
            <div class="group-2">
              <div class="text-wrapper">Contact</div>
              <div class="text-wrapper-3">Get in touch</div>
              <div class="rectangle-2"></div>
            </div>
          </div>
        </a>
        
        <a href="{% url 'staging:services_page' %}">
          <div class="services">
            <div class="group-3">
              <div class="text-wrapper">Services</div>
              <div class="text-wrapper-4">Service i provide</div>
              <div class="rectangle-3"></div>
            </div>
          </div>
        </a>
        
        <div class="overlap">
          <a href="{% url 'staging:blog_page' %}">
            <div class="blog">
              <div class="group-4">
                <div class="text-wrapper-5">Blog</div>
                <div class="text-wrapper-6">What’s New</div>
                <div class="rectangle-4"></div>
              </div>
            </div>
          </a>
          
          <a href="{% url 'staging:home' %}">
            <div class="home">
              <div class="overlap-group"><div class="text-wrapper-7">Home</div></div>
            </div>
          </a>
          
          <a href="{% url 'staging:home' %}">
          <button class="btn">
            <div class="overlap-2">
              <div class="overlap-group-wrapper">
                <div class="overlap-group-2">
                  <div class="rectangle-5"></div>
                  <div class="rectangle-6"></div>
                  <div class="rectangle-7"></div>
                </div>
              </div>
              <div class="close">
                <div class="frame"><div class="text-wrapper-8">- Close</div></div>
              </div>
            </div>
          </button>
        </a>
        </div>
        
        <a href="{% url 'staging:achievements_page' %}">
            <div class="portfolio">
              <div class="achievement">
                <div class="text-wrapper">Achievement</div>
                <div class="text-wrapper-9">My Latest Work</div>
                <div class="rectangle-8"></div>
              </div>
          </div>
        </a>
          
        
        <div class="book-an-appointment">
          <div class="group-5">
            <div class="text-wrapper">Book a Meeting</div>
            <div class="text-wrapper-10">To get to know</div>
            <div class="rectangle-9"></div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}